// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuzomepzfewaglzpvixp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51em9tZXB6ZmV3YWdsenB2aXhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5OTg1OTMsImV4cCI6MjA1NjU3NDU5M30.P8-QgLT0w_5eVGsL-iR9SLYQH2V6Ay-A6FlVADAiA3Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);